# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/sm8250-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter x1q y2q z3q c1q c2q r8q gts7l gts7lwifi gts7xl gts7xlwifi,$(TARGET_DEVICE)),)

endif
